name: Build CI

on:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node.js LTS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          check-latest: true
          cache: pnpm

      - name: Build project
        run: |
          pnpm install
          pnpm build
