name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
           
      - name: Use Node.js LTS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          check-latest: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest      

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            .next/cache
          key: ${{ runner.os }}-pnpm-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-nextjs-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build
            
      - name: Generate sitemap
        run: |
          pnpm run generate-sitemap  

      - name: Add CNAME
        run: |
          echo "mx-space.js.org" > out/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
    env:
      CI: true
